name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up PHP and enable coverage support
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: true

      # Install dependencies
      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-dev --no-scripts
          composer dump-autoload --classmap-authoritative

      # Fix permissions for PHPUnit
      - name: Fix Permissions
        run: chmod +x vendor/bin/phpunit

      # Debug PHP & Composer setup (for troubleshooting)
      - name: Debug PHP & Composer
        run: |
          php -v
          composer show
          ls -la vendor/bin

      # Run the tests and generate code coverage report
      - name: Run Tests
        run: |
          vendor/bin/phpunit --testdox --verbose --coverage-text --coverage-clover=build/logs/coverage.xml

      # List files to confirm paths before uploading
      - name: List build/logs directory to confirm file existence
        run: |
          ls -la build/logs/

      # Upload PHPUnit Test Results
      - name: Upload PHPUnit Test Results
        uses: actions/upload-artifact@v2
        with:
          name: phpunit-test-results
          path: build/test-results.xml  # Make sure this path is correct and exists

      # Upload Coverage Report as an artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/logs/coverage.xml  # This should be generated by --coverage-clover
